module CDC
  module Core
    class ChangeEvent
      EMPTY_METADATA: metadata_hash

      attr_reader operation: Symbol
      attr_reader schema: String
      attr_reader table: String
      attr_reader old_values: event_values?
      attr_reader new_values: event_values?
      attr_reader primary_key: event_values?
      attr_reader transaction_id: untyped
      attr_reader commit_lsn: String?
      attr_reader sequence_number: Integer?
      attr_reader occurred_at: ::Time?
      attr_reader metadata: EventMetadata

      def initialize: (
        operation: Symbol | String,
        schema: String | Symbol,
        table: String | Symbol,
        ?old_values: metadata_hash?,
        ?new_values: metadata_hash?,
        ?primary_key: metadata_hash?,
        ?transaction_id: untyped,
        ?commit_lsn: String?,
        ?sequence_number: Integer?,
        ?occurred_at: ::Time?,
        ?metadata: EventMetadata | metadata_hash
      ) -> void

      def insert?: () -> bool
      def update?: () -> bool
      def delete?: () -> bool
      def qualified_table_name: () -> String
      def changes: () -> ::Array[ColumnChange]
      def to_h: () -> shareable_hash

      private

      def freeze_hash_or_nil: (metadata_hash? hash) -> event_values?
    end
  end
end
