module CDC
  module Core
    class ColumnChange
      attr_reader name: String
      attr_reader old_value: untyped
      attr_reader new_value: untyped

      def initialize: (name: String | Symbol, old_value: untyped, new_value: untyped) -> void
      def changed?: () -> bool
      def to_h: () -> shareable_hash

      private

      def make_value_shareable: (untyped value) -> untyped
    end
  end
end
