module CDC
  module Core
    class Error < ::StandardError
    end

    class InvalidOperationError < Error
    end

    class InvalidOrderingScopeError < Error
    end

    class InvalidOrderingPositionError < Error
    end

    class UnsupportedWorkItemError < Error
    end

    class ProcessorError < Error
    end
  end
end
