module CDC
  module Core
    class EventMetadata
      EMPTY_DATA: metadata_hash

      attr_reader data: shareable_hash

      def initialize: (?metadata_hash data) -> void
      def []: (String | Symbol key) -> untyped
      def to_h: () -> shareable_hash

      private

      def deep_shareable_hash: (metadata_hash hash) -> shareable_hash
      def normalize_key: (untyped key) -> String
      def normalize_value: (untyped value) -> untyped
    end
  end
end
