module CDC
  module Core
    class EventPosition
      attr_reader strategy: Symbol
      attr_reader value: untyped
      attr_reader transaction_id: untyped
      attr_reader sequence_number: Integer?
      attr_reader occurred_at: ::Time?

      def initialize: (
        strategy: Symbol | String,
        value: untyped,
        ?transaction_id: untyped,
        ?sequence_number: Integer?,
        ?occurred_at: ::Time?
      ) -> void

      def to_h: () -> shareable_hash
    end
  end
end
