module CDC
  module Core
    class Filter
      def self.all: () -> Filter
      def self.schema: (String | Symbol name) -> Filter
      def self.table: (String | Symbol name) -> Filter
      def self.qualified_table: (String | Symbol name) -> Filter
      def self.operation: (Symbol | String operation) -> Filter

      def initialize: () { (ChangeEvent event) -> bool } -> void
      def match?: (ChangeEvent event) -> bool
      def =~: (ChangeEvent event) -> bool
      def &: (Filter other) -> Filter
      def |: (Filter other) -> Filter
    end
  end
end
