module CDC
  module Core
    class Observer
      METRIC_NAMES: ::Hash[Symbol, String]
      
      def self.metric_tags: (untyped payload) -> metric_tags
      def self.started_metric_name: () -> String
      def self.succeeded_metric_name: () -> String
      def self.failed_metric_name: () -> String
      def self.skipped_metric_name: () -> String

      def dispatch_started: (ChangeEvent | TransactionEnvelope | ::Array[untyped] event) -> void
      def dispatch_succeeded: (ProcessorResult | ::Array[ProcessorResult] result) -> void
      def dispatch_failed: (ProcessorResult result) -> void
      def dispatch_skipped: (ProcessorResult result) -> void

      def self.change_event_metric_tags: (ChangeEvent event) -> metric_tags
      def self.transaction_envelope_metric_tags: (TransactionEnvelope transaction) -> metric_tags
      def self.processor_result_metric_tags: (ProcessorResult result) -> metric_tags
      def self.batch_metric_tags: (::Array[untyped] batch) -> metric_tags
    end
  end
end
