module CDC
  module Core
    module Operation
      INSERT: :insert
      UPDATE: :update
      DELETE: :delete
      TRUNCATE: :truncate
      MESSAGE: :message

      SUPPORTED: ::Array[Symbol]
      MVP: ::Array[Symbol]

      def self.normalize: (Symbol | String operation) -> Symbol
      def self.supported?: (untyped operation) -> bool

      private

      def normalize: (Symbol | String operation) -> Symbol
      def supported?: (untyped operation) -> bool
    end
  end
end
