module CDC
  module Core
    class OrderingKey
      EMPTY_COMPONENTS: metadata_hash

      attr_reader scope: Symbol
      attr_reader components: shareable_hash

      def initialize: (scope: Symbol | String, ?components: metadata_hash) -> void
      def empty?: () -> bool
      def to_h: () -> shareable_hash
    end
  end
end
