module CDC
  module Core
    class ProcessorChain < Processor
      attr_reader processors: ::Array[_ProcessorLike]
      attr_reader observer: Observer

      def initialize: (::Array[_ProcessorLike] processors, ?observer: Observer?) -> void
      def process: (untyped input) -> ProcessorResult
      def process_many: (::Enumerable[untyped] inputs) -> ::Array[ProcessorResult]

      private

      def normalize_result: (untyped result, untyped input) -> ProcessorResult
      def process_with: (_ProcessorLike processor, untyped input) -> ProcessorResult
      def observe_result: (ProcessorResult result) -> void
    end
  end
end
