module CDC
  module Core
    class SourceAdapter
      def normalize: (untyped input) -> normalized_object
      def normalize_many: (::Enumerable[untyped] inputs) -> ::Array[ChangeEvent | TransactionEnvelope]
    end
  end
end
