module CDC
  module Core
    class TransactionEnvelope
      EMPTY_METADATA: metadata_hash

      attr_reader transaction_id: untyped
      attr_reader events: ::Array[ChangeEvent]
      attr_reader commit_lsn: String?
      attr_reader committed_at: ::Time?
      attr_reader metadata: EventMetadata

      def initialize: (
        transaction_id: untyped,
        events: ::Array[ChangeEvent],
        ?commit_lsn: String?,
        ?committed_at: ::Time?,
        ?metadata: EventMetadata | metadata_hash
      ) -> void

      def empty?: () -> bool
      def size: () -> Integer
      def to_h: () -> shareable_hash
    end
  end
end
